POST http://localhost:5174/admin
Content-Type: application/json

{
    "name": "jhon.doe",
    "email": "jhon.doe@example.com",
    "password": "12345678"
}
###
DELETE http://localhost:5174/logout
###
GET http://localhost:5174/admin/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRzYWxtYW5pQGV4YW1wbGUuY29tIiwicGFzc3dvcmQiOiIxMjM0NTY3OCIsImlhdCI6MTY5OTYyNjk5NywiZXhwIjoxNjk5NjI2OTk3fQ.41iR9zsP73Mwps-PGI8HLL5xvxMXSM4HJz9hBy9q6gs
###
POST http://localhost:5174/login
Content-Type: application/json

{
    "email": "tsalmani@example.com",
    "password": "12345678"
}
################################
POST http://localhost:5174/login
Content-Type: application/json

{
    "email": "tsalmani@example.com",
    "password": "12345678"
}
####
delete http://localhost:5174/tiket
Content-Type: application/json

[
    {
        "_id": "6558e18216ec5c59d7f1663e",
        "name": "gg",
        "noWa": "343434",
        "tanggalLahir": "2023-11-17",
        "kdTempat": [
            "kd1",
            "kd3",
            "kd4",
            "kd5"
        ],
        "sesiBooking": "10:00:00",
        "tanggalBooking": "2023-11-25",
        "waktuPesan": "19,November 2023",
        "isVerified": true,
        "__v": 0
    },
    {
        "_id": "6558cba416ec5c59d7f163dc",
        "name": "clientUserbaru",
        "noWa": "234543345",
        "tanggalLahir": "2023-11-02",
        "kdTempat": [
            "kd39",
            "kd40",
            "kd35",
            "kd230",
            "kd25",
            "kd20",
            "kd10",
            "kd15",
            "kd5"
        ],
        "sesiBooking": "16:00:00",
        "tanggalBooking": "2023-11-18",
        "waktuPesan": "18,November 2023",
        "isVerified": true,
        "__v": 0
    }
]


################################
POST http://localhost:5174/tiket
Content-Type: application/json

{
    "name": "client1",
    "noWa": "234543",
    "tanggalLahir": "2023-11-16",
    "kdTempat": [
      "kd4",
      "kd9"
    ],
    "sesiBooking": "16:00:00",
    "tanggalBooking": "2023-10-1",
    "waktuPesan": "2023-10-11",
    "isVerified": true
}
################################
POST http://localhost:5174/tiket
Content-Type: application/json

{
    "name": "client2",
    "noWa": "234543",
    "tanggalLahir": "2023-11-16",
    "kdTempat": [
      "kd4",
      "kd9"
    ],
    "sesiBooking": "16:00:00",
    "tanggalBooking": "2023-11-15",
    "waktuPesan": "2023-11-12",
    "isVerified": true
}
################################
POST http://localhost:5174/tiket
Content-Type: application/json

{
    "name": "client3",
    "noWa": "234543",
    "tanggalLahir": "2023-11-16",
    "kdTempat": [
      "kd4",
      "kd9"
    ],
    "sesiBooking": "16:00:00",
    "tanggalBooking": "2023-11-15",
    "waktuPesan": "2023-11-13",
    "isVerified": true
}
################################
POST http://localhost:5174/tiket
Content-Type: application/json

{
    "name": "client4",
    "noWa": "234543",
    "tanggalLahir": "2023-11-16",
    "kdTempat": [
      "kd4",
      "kd9"
    ],
    "sesiBooking": "16:00:00",
    "tanggalBooking": "2023-11-15",
    "waktuPesan": "2023-11-13",
    "isVerified": true
}
################################
POST http://localhost:5174/tiket
Content-Type: application/json

{
    "name": "client5",
    "noWa": "234543",
    "tanggalLahir": "2023-11-16",
    "kdTempat": [
      "kd4",
      "kd9"
    ],
    "sesiBooking": "16:00:00",
    "tanggalBooking": "2023-11-15",
    "waktuPesan": "2023-11-14",
    "isVerified": true
}
################################
POST http://localhost:5174/tiket
Content-Type: application/json

{
    "name": "client6",
    "noWa": "234543",
    "tanggalLahir": "2023-11-16",
    "kdTempat": [
      "kd4",
      "kd9"
    ],
    "sesiBooking": "16:00:00",
    "tanggalBooking": "2023-11-15",
    "waktuPesan": "2023-11-15",
    "isVerified": true
}

################################
POST http://localhost:5174/tiket
Content-Type: application/json

{
    "name": "clientBaru2",
    "noWa": "234543",
    "tanggalLahir": "2023-11-16",
    "kdTempat": [
      "kd4",
      "kd9"
    ],
    "sesiBooking": "16:00:00",
    "tanggalBooking": "2023-11-15"
}
######
POST http://localhost:5174/tiket
Content-Type: application/json

{
    "name": "client1",
    "noWa": "234543",
    "tanggalLahir": "2023-11-16",
    "kdTempat": [
      "kd4",
      "kd9"
    ],
    "sesiBooking": "16:00:00",
    "tanggalBooking": "2023-10-1",
    "waktuPesan": "2023-10-11",
    "isVerified": true
}
################################
POST http://localhost:5174/tiket
Content-Type: application/json

{
    "name": "client7",
    "noWa": "234543",
    "tanggalLahir": "2023-11-16",
    "kdTempat": [
      "kd4",
      "kd9"
    ],
    "sesiBooking": "16:00:00",
    "tanggalBooking": "2023-11-15",
    "waktuPesan": "2023-11-12",
    "isVerified": true
}
################################
POST http://localhost:5174/tiket
Content-Type: application/json

{
    "name": "client8",
    "noWa": "234543",
    "tanggalLahir": "2023-11-16",
    "kdTempat": [
      "kd4",
      "kd1"
    ],
    "sesiBooking": "16:00:00",
    "tanggalBooking": "2023-11-15",
    "waktuPesan": "2023-11-13",
    "isVerified": true
}
################################
POST http://localhost:5174/tiket
Content-Type: application/json

{
    "name": "client9",
    "noWa": "234543",
    "tanggalLahir": "2023-11-16",
    "kdTempat": [
      "kd4",
      "kd9"
    ],
    "sesiBooking": "16:00:00",
    "tanggalBooking": "2023-11-15",
    "waktuPesan": "2023-11-13",
    "isVerified": true
}
################################
POST http://localhost:5174/tiket
Content-Type: application/json

{
    "name": "client10",
    "noWa": "234543",
    "tanggalLahir": "2023-11-16",
    "kdTempat": [
      "kd4",
      "kd3"
    ],
    "sesiBooking": "16:00:00",
    "tanggalBooking": "2023-11-15",
    "waktuPesan": "2023-11-14",
    "isVerified": true
}
################################
POST http://localhost:5174/tiket
Content-Type: application/json

{
    "name": "client11",
    "noWa": "234543",
    "tanggalLahir": "2023-11-16",
    "kdTempat": [
      "kd4",
      "kd5"
    ],
    "sesiBooking": "16:00:00",
    "tanggalBooking": "2023-11-15",
    "waktuPesan": "2023-11-15",
    "isVerified": true
}

################################
POST http://localhost:5174/tiket
Content-Type: application/json

{
    "name": "clientBaru222",
    "noWa": "234543",
    "tanggalLahir": "2023-11-16",
    "kdTempat": [
      "kd8",
      "kd1"
    ],
    "sesiBooking": "16:00:00",
    "tanggalBooking": "2023-11-15"
}